// <auto-generated />
using System;
using MegaStream.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MegaStream.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261002070719_AddDeviceExperience")]
    partial class AddDeviceExperience
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MegaStream.Server.Models.ActivationCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("CodeLast4")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("InstallationId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("LicenseId")
                        .HasColumnType("char(36)");

                    b.Property<string>("PollTokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("CodeHash")
                        .IsUnique();

                    b.HasIndex("InstallationId");

                    b.HasIndex("LicenseId");

                    b.HasIndex("Status", "ExpiresAt");

                    b.ToTable("ActivationCodes");
                });

            modelBuilder.Entity("MegaStream.Server.Models.AdminNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<Guid?>("TargetInstallationId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("TargetInstallationId", "CreatedAt");

                    b.ToTable("AdminNotifications");
                });

            modelBuilder.Entity("MegaStream.Server.Models.DevicePolicyAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("InstallationId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("NewAllowLocalExit")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NewKioskMode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<bool>("OldAllowLocalExit")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("OldKioskMode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("InstallationId", "CreatedAt");

                    b.ToTable("DevicePolicyAudits");
                });

            modelBuilder.Entity("MegaStream.Server.Models.DeviceSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AppVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("ClientSessionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ExitReason")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<Guid>("InstallationId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("LastHeartbeatAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("MemoryBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ClientSessionId");

                    b.HasIndex("LastHeartbeatAt");

                    b.HasIndex("InstallationId", "ClientSessionId")
                        .IsUnique();

                    b.ToTable("DeviceSessions");
                });

            modelBuilder.Entity("MegaStream.Server.Models.DiagnosticEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AppVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("AudioCodec")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("ChannelName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Container")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeviceVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<Guid>("EventId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("InstallationId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<long?>("MemoryBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("StackTrace")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("varchar(4096)");

                    b.Property<string>("VideoCodec")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("Category", "OccurredAt");

                    b.HasIndex("InstallationId", "EventId")
                        .IsUnique();

                    b.HasIndex("InstallationId", "OccurredAt");

                    b.ToTable("DiagnosticEvents");
                });

            modelBuilder.Entity("MegaStream.Server.Models.Installation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ActivatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("AllowLocalExit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<bool>("AllowSubscriptionDetails")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("AppVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CredentialBinding")
                        .IsRequired()
                        .HasMaxLength(43)
                        .HasColumnType("varchar(43)");

                    b.Property<string>("DeviceModel")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("FingerprintHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("KioskMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasDefaultValue("off");

                    b.Property<DateTime?>("LastLeaseExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("LicenseId")
                        .HasColumnType("char(36)");

                    b.Property<string>("LocalSubscriptionsJson")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LocalSubscriptionsReportedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("MacAddress")
                        .HasMaxLength(17)
                        .HasColumnType("varchar(17)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("OsVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("FingerprintHash");

                    b.HasIndex("LastLeaseExpiresAt");

                    b.HasIndex("LastSeenAt");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("LicenseId", "Status");

                    b.ToTable("Installations");
                });

            modelBuilder.Entity("MegaStream.Server.Models.License", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("KeyLast4")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("MaxInstallations")
                        .HasColumnType("int");

                    b.Property<int>("OfflineGraceDays")
                        .HasColumnType("int");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ValidUntil")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("KeyHash")
                        .IsUnique();

                    b.HasIndex("Status", "ValidUntil");

                    b.ToTable("Licenses");
                });

            modelBuilder.Entity("MegaStream.Server.RemoteProviders.Core.ProviderAssignmentReport", b =>
                {
                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("InstallationId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("LastReportedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("ProfileRevision")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ProviderReportedExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ProviderReportedMaxConnections")
                        .HasColumnType("int");

                    b.Property<string>("SafeErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("AssignmentId");

                    b.HasIndex("InstallationId");

                    b.HasIndex("AssignmentId", "InstallationId")
                        .IsUnique();

                    b.ToTable("RemoteProviderReports", (string)null);
                });

            modelBuilder.Entity("MegaStream.Server.RemoteProviders.Core.RemoteProviderAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("InstallationId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Policy")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("char(36)");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("InstallationId", "Revision");

                    b.HasIndex("ProfileId", "InstallationId")
                        .IsUnique();

                    b.ToTable("RemoteProviderAssignments", (string)null);
                });

            modelBuilder.Entity("MegaStream.Server.RemoteProviders.Core.RemoteProviderProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<byte[]>("EncryptedPayload")
                        .IsRequired()
                        .HasMaxLength(32768)
                        .HasColumnType("longblob");

                    b.Property<string>("KeyVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Revision");

                    b.ToTable("RemoteProviderProfiles", (string)null);
                });

            modelBuilder.Entity("MegaStream.Server.RemoteProviders.Core.RemoteProviderRevisionSequence", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("RemoteProviderRevisionSequence", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Revision = 0L
                        });
                });

            modelBuilder.Entity("MegaStream.Server.Updates.DeviceUpdateCommand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("AckAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DownloadedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime?>("FailedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("InstallPromptedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("InstallationId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("InstalledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("char(36)");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ReleaseId");

                    b.HasIndex("InstallationId", "ReleaseId")
                        .IsUnique();

                    b.ToTable("DeviceUpdateCommands", (string)null);
                });

            modelBuilder.Entity("MegaStream.Server.Updates.DeviceUpdateState", b =>
                {
                    b.Property<Guid>("InstallationId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Abi")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<int>("Sdk")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("VersionCode")
                        .HasColumnType("bigint");

                    b.HasKey("InstallationId");

                    b.ToTable("DeviceUpdateStates", (string)null);
                });

            modelBuilder.Entity("MegaStream.Server.Updates.UpdateRelease", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Abi")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<bool>("Mandatory")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MinSdk")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(4096)
                        .HasColumnType("varchar(4096)");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("SigningCertificateSha256")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<long>("VersionCode")
                        .HasColumnType("bigint");

                    b.Property<string>("VersionName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("VersionCode")
                        .IsUnique();

                    b.ToTable("UpdateReleases", (string)null);
                });

            modelBuilder.Entity("MegaStream.Server.V1.V1DiagnosticReceipt", b =>
                {
                    b.Property<Guid>("InstallationId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("EventId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AppSessionId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<long>("OccurredAt")
                        .HasColumnType("bigint");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasMaxLength(16384)
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint");

                    b.HasKey("InstallationId", "EventId");

                    b.HasIndex("ReceivedAt");

                    b.ToTable("V1DiagnosticReceipts", (string)null);
                });

            modelBuilder.Entity("MegaStream.Server.V1.V1InstallationMetadata", b =>
                {
                    b.Property<Guid>("InstallationId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Abi")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<int>("AndroidApi")
                        .HasColumnType("int");

                    b.Property<int>("AppVersionCode")
                        .HasColumnType("int");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<bool>("ManagedDevice")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<Guid>("RegistrationIdempotencyKey")
                        .HasColumnType("char(36)");

                    b.HasKey("InstallationId");

                    b.ToTable("V1InstallationMetadata", (string)null);
                });

            modelBuilder.Entity("MegaStream.Server.V1.V1SessionState", b =>
                {
                    b.Property<Guid>("InstallationId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AppSessionId")
                        .HasColumnType("char(36)");

                    b.Property<long?>("AvailableSystemBytes")
                        .HasColumnType("bigint");

                    b.Property<long?>("JavaMaxBytes")
                        .HasColumnType("bigint");

                    b.Property<long?>("JavaUsedBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastAcceptedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("LastSequence")
                        .HasColumnType("bigint");

                    b.Property<bool?>("LowMemory")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<long?>("NativeHeapBytes")
                        .HasColumnType("bigint");

                    b.Property<long?>("PssBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("RecoveredExitAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RecoveredExitEvidence")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("RecoveredExitReason")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("InstallationId", "AppSessionId");

                    b.HasIndex("AppSessionId")
                        .IsUnique();

                    b.HasIndex("LastAcceptedAt");

                    b.ToTable("V1SessionStates", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MegaStream.Server.Models.ActivationCode", b =>
                {
                    b.HasOne("MegaStream.Server.Models.Installation", "Installation")
                        .WithMany()
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MegaStream.Server.Models.License", "License")
                        .WithMany()
                        .HasForeignKey("LicenseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Installation");

                    b.Navigation("License");
                });

            modelBuilder.Entity("MegaStream.Server.Models.AdminNotification", b =>
                {
                    b.HasOne("MegaStream.Server.Models.Installation", "TargetInstallation")
                        .WithMany()
                        .HasForeignKey("TargetInstallationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("TargetInstallation");
                });

            modelBuilder.Entity("MegaStream.Server.Models.DevicePolicyAudit", b =>
                {
                    b.HasOne("MegaStream.Server.Models.Installation", "Installation")
                        .WithMany()
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Installation");
                });

            modelBuilder.Entity("MegaStream.Server.Models.DeviceSession", b =>
                {
                    b.HasOne("MegaStream.Server.Models.Installation", "Installation")
                        .WithMany()
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Installation");
                });

            modelBuilder.Entity("MegaStream.Server.Models.DiagnosticEvent", b =>
                {
                    b.HasOne("MegaStream.Server.Models.Installation", "Installation")
                        .WithMany()
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Installation");
                });

            modelBuilder.Entity("MegaStream.Server.Models.Installation", b =>
                {
                    b.HasOne("MegaStream.Server.Models.License", "License")
                        .WithMany()
                        .HasForeignKey("LicenseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("License");
                });

            modelBuilder.Entity("MegaStream.Server.RemoteProviders.Core.ProviderAssignmentReport", b =>
                {
                    b.HasOne("MegaStream.Server.RemoteProviders.Core.RemoteProviderAssignment", null)
                        .WithOne()
                        .HasForeignKey("MegaStream.Server.RemoteProviders.Core.ProviderAssignmentReport", "AssignmentId", "InstallationId")
                        .HasPrincipalKey("MegaStream.Server.RemoteProviders.Core.RemoteProviderAssignment", "Id", "InstallationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MegaStream.Server.RemoteProviders.Core.RemoteProviderAssignment", b =>
                {
                    b.HasOne("MegaStream.Server.Models.Installation", null)
                        .WithMany()
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MegaStream.Server.RemoteProviders.Core.RemoteProviderProfile", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MegaStream.Server.Updates.DeviceUpdateCommand", b =>
                {
                    b.HasOne("MegaStream.Server.Models.Installation", "Installation")
                        .WithMany()
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MegaStream.Server.Updates.UpdateRelease", "Release")
                        .WithMany()
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Installation");

                    b.Navigation("Release");
                });

            modelBuilder.Entity("MegaStream.Server.Updates.DeviceUpdateState", b =>
                {
                    b.HasOne("MegaStream.Server.Models.Installation", "Installation")
                        .WithOne()
                        .HasForeignKey("MegaStream.Server.Updates.DeviceUpdateState", "InstallationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Installation");
                });

            modelBuilder.Entity("MegaStream.Server.V1.V1DiagnosticReceipt", b =>
                {
                    b.HasOne("MegaStream.Server.Models.Installation", null)
                        .WithMany()
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MegaStream.Server.V1.V1InstallationMetadata", b =>
                {
                    b.HasOne("MegaStream.Server.Models.Installation", null)
                        .WithOne()
                        .HasForeignKey("MegaStream.Server.V1.V1InstallationMetadata", "InstallationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MegaStream.Server.V1.V1SessionState", b =>
                {
                    b.HasOne("MegaStream.Server.Models.Installation", null)
                        .WithMany()
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
